POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "World Animal Protection Blog",
    "author": "WAP ORG",
    "url": "https://www.worldanimalprotection.org/latest/blogs/",
    "likes": 103
}